### ISSUE TITLE
subscribe function has issues

### ISSUE THREAD

**Issue by kalmenchia** [hashme/firebase-python#4]
Hi , 

By following the "subscribe" function example , 

#>>> import pprint from pprint
#>>> S = firebase.subscriber(URL, pprint)  

and after i executed 

#>>> S.start() 

the follow errors show up ,

#>>> Exception in thread Thread-242:

Traceback (most recent call last):
  File "/usr/local/python/2.7.9//Versions/2.7/lib/python2.7/threading.py", line 810, inr
    self.run()
  File "firebase.py", line 44, in run
    self.sse = ClosableSSEClient(self.URL)
  File "firebase.py", line 16, in __init__
    super(ClosableSSEClient, self).__init__(*args, **kwargs)
TypeError: __init__() takes at least 4 arguments (2 given)

Can any one please advice ?
thanks.

**Comment by shariq** [comment]
hey @kalmenchia I'm sorry but no longer maintaining this repo - will leave your issue open for others
